fos_user:
    db_driver:      orm
    firewall_name:  main

    # changing class configuration needs to update sonata_user.yml file accordingly
    user_class:     Application\Sonata\UserBundle\Entity\User
    #user_class:   Sonata\UserBundle\Entity\BaseUser
    #user_class: AppBundle\Entity\User
    
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    registration:
        form:
            type: AppBundle\Form\RegistrationType
            #type: FOS\UserBundle\Form\Type\RegistrationFormType
            #name: fos_user_registration_form
            validation_groups: [Registration, Default]
        confirmation:
            enabled: true
            template: '@FOSUser/Registration/email.txt.twig'

    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
        #group_class:   Sonata\UserBundle\Entity\BaseGroup
        group_manager: sonata.user.orm.group_manager

    service:
        user_manager: sonata.user.orm.user_manager