<?php

namespace AppBundle\Repository;

/**
 * LegendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LegendRepository extends \Doctrine\ORM\EntityRepository
{
	public function getNuclideByLegends(array $legends)
	{
		$qb = $this->_em->createQueryBuilder();

		$qb
		->select('ln')
		->from('AppBundle:LegendNuclide', 'ln')
		;

		if(null !== $legends) {
			$qb
			->where('ln.legend IN (:legends)')
			->setParameter('legends', $legends, \Doctrine\DBAL\Connection::PARAM_STR_ARRAY)
			->orderBy('ln.position', 'ASC')
			;
		}
		return $qb->getQuery()->getResult();
	}

	public function search($data, $page = 0, $max = NULL, $getResult = true)
	{
		$qb = $this->_em->createQueryBuilder();
		$query = isset($data['query']) && $data['query']?$data['query']:null;

		$qb
		->select('u')
		->from('AppBundle:Station', 'u')
		;

		if ($query) {
			$qb
			->andWhere('u.code like :query')
			->setParameter('query', "%".$query."%")
			;
		}

		if ($max) {
			$preparedQuery = $qb->getQuery()
			->setMaxResults($max)
			->setFirstResult($page * $max)
			;
		} else {
			$preparedQuery = $qb->getQuery();
		}

		return $getResult?$preparedQuery->getResult():$preparedQuery;
	}




}