<?php

namespace AppBundle\Repository;

/**
 * NuclideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NuclideRepository extends \Doctrine\ORM\EntityRepository
{
	public function getNuclidesList($station, $legend)
	{
		$qb = $this->_em->createQueryBuilder();
	
		$qb
		->select('n')
		->from('AppBundle:Nuclide', 'n')
		->join('n.legends', 'ln')
		->join('AppBundle:Result', 'r', \Doctrine\ORM\Query\Expr\Join::WITH, 'n = r.nuclide')
		->join('AppBundle:Measurement', 'm', \Doctrine\ORM\Query\Expr\Join::WITH, 'm = r.measurement')
		->join('AppBundle:Sample', 's', \Doctrine\ORM\Query\Expr\Join::WITH, 's = m.sample')
		
		;
	
		$qb
		->andWhere('n.active=1')
		->andWhere('s.station=:station')
		->andWhere('ln.legend=:legend')
		->addOrderBy("ln.position")
		->setParameter('station', $station)
		->setParameter('legend', $legend)
		;

		return $qb->getQuery()->getResult();
	
	}

}
