<?php

namespace AppBundle\Repository;

/**
 * PredefinedNuclideListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PredefinedNuclideListRepository extends \Doctrine\ORM\EntityRepository
{
}
