<?php

namespace AppBundle\Repository;

/**
 * PredefinedNuclideListNuclideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PredefinedNuclideListNuclideRepository extends \Doctrine\ORM\EntityRepository
{
}
