<?php

namespace AppBundle\Repository;

/**
 * ResultCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
