<?php

namespace AppBundle\Repository;

/**
 * StationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StationRepository extends \Doctrine\ORM\EntityRepository
{
	public function last_results_by_nuclide()
	{
		
	}
	
	public function search($data, $page = 0, $max = NULL, $getResult = true)
	{
		$qb = $this->_em->createQueryBuilder();
		$query = isset($data['query']) && $data['query']?$data['query']:null;
	
		$qb
		->select('u')
		->from('AppBundle:Station', 'u')
		;
	
		if ($query) {
			$qb
			->andWhere('u.code like :query')
			->setParameter('query', "%".$query."%")
			;
		}
	
		if ($max) {
			$preparedQuery = $qb->getQuery()
			->setMaxResults($max)
			->setFirstResult($page * $max)
			;
		} else {
			$preparedQuery = $qb->getQuery();
		}
	
		return $getResult?$preparedQuery->getResult():$preparedQuery;
	}
	
	
	public function getResultsByNuclide($nuclide)
	{
		$qb = $this->_em->createQueryBuilder();
		
		$qb
		->select('u')
		->from('AppBundle:Sample', 'u')
		;
		
		$qb
		->andWhere('u.station = :station')
		->setParameter('station', $this->getId())
		;
		
		return $qb->getQuery()->getResult();
	}

}