imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    
    # FOS Bundles
    - { resource: fos/fos_user.yml }
    
    # Sonata Core Bundles
    
    # Sonata Feature Bundles
    - { resource: sonata/sonata_admin.yml }
    - { resource: sonata/sonata_user.yml }
    
    # project specific
    - { resource: "@AppBundle/Resources/config/admin.yml" }
    
    # Ivory CKEditor
    - { resource: ivory/ivory_ckeditor.yml }
    # Ivory Google Map
    - { resource: ivory/ivory_google_map.yml }
    
    

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    app.locales: en|fr|de|it
    google_api_key: "AIzaSyAxq534Dz9_5Jhq1MpYFivw4XTumQEoOSg"

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    globals:
        google_api_key: '%google_api_key%'
        measureSrv: "@app.lastresult"
        
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    
    form_themes:
        - 'SonataFormatterBundle:Form:formatter.html.twig'
        - 'SonataCoreBundle:Form:colorpicker.html.twig'
        - 'XmonColorPickerTypeBundle:Form:fields.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_mysql
                host: '%database_host%'
                port: '%database_port%'
                dbname: '%database_name%'
                user: '%database_user%'
                password: '%database_password%'
                charset: UTF8
            envira:
                server_version: 14.14
                driver: mysqli
                host: '%db_envira_host%'
                port: '%db_envira_port%'
                dbname: '%db_envira_name%'
                user: '%db_envira_user%'
                password: '%db_envira_password%'
                charset: UTF8
             
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                        alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
                        is_bundle: false
                    gedmo_translator:
                        type: annotation
                        prefix: Gedmo\Translator\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                        alias: GedmoTranslator # (optional) it will default to the name set for the mapping
                        is_bundle: false
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # (optional) it will default to the name set for the mappingmapping
                        is_bundle: false
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        alias: GedmoTree # (optional) it will default to the name set for the mapping
                        is_bundle: false
                    FOSUserBundle: ~
                    ApplicationSonataUserBundle: ~
                    SonataUserBundle: ~
                    ApplicationSonataMediaBundle: ~
                    SonataMediaBundle: ~
                    

        
# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    #host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
    

       
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    bundles:
        - 'XmonColorPickerTypeBundle'
    filters:
        lessphp:
            node: /usr/local/bin/node
            node_paths: [/usr/local/lib/node_modules]
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'

# Sonata Configuration

              
    
sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts: [admin]
        sonata.block.service.text:
        sonata.block.service.rss:
        
sonata_formatter:
    formatters:
        markdown:
            service: sonata.formatter.text.markdown
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig #keep this commented unless you are using media bundle.


        text:
            service: sonata.formatter.text.text
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig


        rawhtml:
            service: sonata.formatter.text.raw
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig


        richhtml:
            service: sonata.formatter.text.raw
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig


        twig:
            service: sonata.formatter.text.twigengine
            extensions: [] # Twig formatter cannot have extensions

knp_doctrine_behaviors:
    translatable: true
    
a2lix_translation_form:
    locale_provider: default       
    locales: [fr, de, it, en]     
    default_locale: fr             
    required_locales: [fr, de]         
    templating: "A2lixTranslationFormBundle::default.html.twig"     
            
stof_doctrine_extensions:
    default_locale: fr
    orm:
        default:
            tree: true
            timestampable: true
            sortable: true

sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
         # Block Stat créé pour le DashBoard
        sonata.block.service.stat: ~
            
sonata_media:
    # if you don't use default namespace configuration
    #class:
    #    media: MyVendor\MediaBundle\Entity\Media
    #    gallery: MyVendor\MediaBundle\Entity\Gallery
    #    gallery_has_media: MyVendor\MediaBundle\Entity\GalleryHasMedia
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here
    default_context: default # you need to set a context
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  "%kernel.root_dir%/../web/uploads/media"
            create:     false
            
            
waldo_datatable:
    all:
        search:           false
    js:
        pageLength: "5"
        lengthMenu: [[5,10, 25, 50, -1], [5,10, 25, 50, 'All']]
        dom: '<"clearfix"lf>rtip'
        jQueryUI: "false"
  
apy_data_grid:
    persistence: true
    limits: [5, 10, 15]      
    
fos_js_routing:
    routes_to_expose: [ adv, advlist, ... ]
