
_front:
    resource: routing_front.yml
    prefix:   /{_locale}
    requirements:
        _locale: de|fr|it|en

_admin:
    resource: routing_admin.yml
    prefix:   /admin
    

home:
    path: /
    defaults:
        _controller: AppBundle:Radenviro:index

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
