# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    
    gedmo.listener.sortable:
        class: Gedmo\Sortable\SortableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    
    app.admin.automaticNetworkStation:
        class: AppBundle\Admin\AutomaticNetworkStationAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, label: "Automatic Network Station" }
        arguments:
          - ~
          - AppBundle\Entity\AutomaticNetworkStation
          - 'PixSortableBehaviorBundle:SortableAdmin' # define the new controller via the third argument
        calls:
          - [ setContainer, [ "@service_container" ] ]
          - [ setPositionService, [ "@pix_sortable_behavior.position" ] ] 
