sonata_admin:
    templates:
        edit:                AppBundle:CRUD:edit.html.twig
    
    dashboard:
        blocks:
            - { position: left, type: sonata.admin.block.admin_list }
            -
                position: right
                type: sonata.block.service.text
                settings:
                    content: >
                        <h2>Welcome to the Sonata Admin</h2>
                        <p>This is a <code>sonata.block.service.text</code> from the Block
                        Bundle, you can create and add new block in these area by configuring
                        the <code>sonata_admin</code> section.</p> <br /> For instance, here
                        a RSS feed parser (<code>sonata.block.service.rss</code>):
            #- { position: top,  class: col-md-12, type: sonata.admin.block.admin_list }
            
#            -
#                class:    col-lg-3 col-xs-6
#                position: top
#                type:     sonata.admin.block.stats
#                settings:
#                    code: sonata.news.admin.comment
#                    icon: fa-comments
#                    text: Open Comment
#                    filters:
#                        status: { type: 3, value: 0 } # 3 => NumberType::TYPE_EQUAL    
                        
#            - { roles: [ROLE_SUPER_ADMIN], position: left, type: sonata.block.service.text, settings: { content: "<div class='panel panel-default'><div class='panel-heading'><h3 class='panel-title'>Welcome!</h3></div><div class='panel-body'>You can customize this dashboard by editing the <code>sonata_admin.yml</code> file. The current dashboard presents the recent items from the NewsBundle and a non-statistical e-commerce information.</div></div>"} }


        groups:
            sonata.admin.group.frontend:
                label:           ofsp_frontend
                label_catalogue: AppBundle
                icon:            '<i class="fa fa-th"></i>'
                items:
                    - app.admin.legend
                    - app.admin.mapZoom
                    - app.admin.page
            
            sonata.admin.group.content:
                label:           ofsp_content
                label_catalogue: AppBundle
                icon:            '<i class="fa fa-th"></i>'
                items:
                    - app.admin.automaticNetwork
                    - app.admin.automaticNetworkStation
                    - app.admin.networkCategory
                    - app.admin.network
                    - app.admin.stationType
                    - app.admin.station
                    - app.admin.siteType
                    - app.admin.site
                                        
                    
            sonata.admin.group.config:
                label:           ofsp_config
                label_catalogue: AppBundle
                icon:            '<i class="fa fa-th"></i>'
                items:
                    - app.admin.country
                    #- app.admin.bagCode
                    - app.admin.nuclide
                    
                
                        
            sonata.admin.group.administration:
                label:           sonata_administration
                label_catalogue: SonataAdminBundle
                icon:            '<i class="fa fa-cogs"></i>'
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group
                    #- sonata.page.admin.site
                    #- sonata.notification.admin.message
                    
                    
                    
                    
                    
                    
                    
                 