# src/AppBundle/Resources/config/admin.yml
    
services:
    app.admin.page:
        class: AppBundle\Admin\PageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "admin.group.frontend", label: "admin.menu.page" }
        arguments:
            - ~
            - AppBundle\Entity\Page
            - ~
        calls:
            - [ setTranslationDomain, [messages]]
    
    app.admin.isotopestationfluctuation:
        class: AppBundle\Admin\IsotopeStationFluctuationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "admin.group.frontend", label: "admin.menu.fluctuation" }
        arguments:
            - ~
            - AppBundle\Entity\IsotopeStationFluctuation
            - 'PixSortableBehaviorBundle:SortableAdmin'
            - ~
        calls:
            - [ setTranslationDomain, [messages]]
            
    app.admin.legend:
        class: AppBundle\Admin\LegendAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "admin.group.frontend", label: "admin.menu.legend" }
        arguments:
            - ~
            - AppBundle\Entity\Legend
            - 'PixSortableBehaviorBundle:SortableAdmin'
            - ~
        calls:
            - [ setTranslationDomain, [messages]]
            #- [ addChild, ['@app.admin.legendstation']]
    
    app.admin.legendstation:
        class: AppBundle\Admin\LegendStationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "admin.group.frontend", label: "admin.menu.legend_station" }
        arguments:
            - ~
            - AppBundle\Entity\LegendStation
            - 'PixSortableBehaviorBundle:SortableAdmin'
            - ~
        calls:
            - [ setTranslationDomain, [messages]]
            
    app.admin.legendnuclide:
        class: AppBundle\Admin\LegendNuclideAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "admin.group.frontend", label: "admin.menu.legend_nuclide" }
        arguments:
            - ~
            - AppBundle\Entity\LegendNuclide
            - 'PixSortableBehaviorBundle:SortableAdmin'
            - ~
        calls:
            - [ setTranslationDomain, [messages]]
                    
           
    app.admin.siteType:
        class: AppBundle\Admin\SiteTypeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "admin.group.frontend", label: "admin.menu.site_type" }
        arguments:
            - ~
            - AppBundle\Entity\SiteType
            - 'PixSortableBehaviorBundle:SortableAdmin'
            - ~
        calls:
            - [ setTranslationDomain, [messages]]
            
    app.admin.site:
        class: AppBundle\Admin\SiteAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "admin.menu.site" }
        arguments:
            - ~
            - AppBundle\Entity\Site
            - 'PixSortableBehaviorBundle:SortableAdmin'
            - ~
        calls:
            - [ setTranslationDomain, [messages]]
            
    app.admin.sitestation:
        class: AppBundle\Admin\SiteStationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "admin.group.frontend", label: "admin.menu.site_station" }
        arguments:
            - ~
            - AppBundle\Entity\SiteStation            
            - ~
        calls:
            - [ setTranslationDomain, [messages]]
            
    app.admin.automaticNetwork:
        class: AppBundle\Admin\AutomaticNetworkAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "admin.menu.automatic_network" }
        arguments:
            - ~
            - AppBundle\Entity\AutomaticNetwork
            - 'PixSortableBehaviorBundle:SortableAdmin'
            - ~
        calls:
            - [ setTranslationDomain, [messages]]
    
    app.admin.automaticNetworkStation:
        class: AppBundle\Admin\AutomaticNetworkStationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "admin.menu.automatic_network_station" }
        arguments:
            - ~
            - AppBundle\Entity\AutomaticNetworkStation
            - ~
        calls:
            - [ setTranslationDomain, [messages]]
            
    app.admin.station:
        class: AppBundle\Admin\StationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "admin.menu.station" }
        arguments:
            - ~
            - AppBundle\Entity\Station
            - ~
        calls:
            - [ setTranslationDomain, [messages]]
   
    app.admin.stationType:
        class: AppBundle\Admin\StationTypeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "admin.menu.station_type" }
        arguments:
            - ~
            - AppBundle\Entity\StationType
            - ~
        calls:
            - [ setTranslationDomain, [messages]]
   
    app.admin.networkCategory:
        class: AppBundle\Admin\NetworkCategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "admin.menu.network_category" }
        arguments:
            - ~
            - AppBundle\Entity\NetworkCategory
            - ~
        calls:
            - [ setTranslationDomain, [messages]]
            
    app.admin.network:
        class: AppBundle\Admin\NetworkAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "admin.menu.network" }
        arguments:
            - ~
            - AppBundle\Entity\Network
            - ~
        calls:
            - [ setTranslationDomain, [messages]]
            
    app.admin.nuclide:
        class: AppBundle\Admin\NuclideAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "admin.menu.nuclide" }
        arguments:
            - ~
            - AppBundle\Entity\Nuclide
            - ~
        calls:
            - [ setTranslationDomain, [messages]]
            
    app.admin.predefinednuclidelist:
        class: AppBundle\Admin\PredefinedNuclideListAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "admin.menu.predefinednuclidelist" }
        arguments:
            - ~
            - AppBundle\Entity\PredefinedNuclideList
            - 'PixSortableBehaviorBundle:SortableAdmin'
        calls:
            - [ setTranslationDomain, [messages]]
            
    app.admin.mapZoom:
        class: AppBundle\Admin\MapZoomAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "admin.menu.zoom" }
        arguments:
            - ~
            - AppBundle\Entity\MapZoom
            - ~
        calls:
            - [ setTranslationDomain, [messages]]
            
#    app.admin.bagCode:
#        class: AppBundle\Admin\BagCodeAdmin
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: "Content", label: "admin.menu.bag_code" }
#        arguments:
#            - ~
#            - AppBundle\Entity\BagCode
#            - ~
#        calls:
#            - [ setTranslationDomain, [messages]]
            
    app.admin.country:
        class: AppBundle\Admin\CountryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "admin.menu.country" }
        arguments:
            - ~
            - AppBundle\Entity\Country
            - ~
        calls:
            - [ setTranslationDomain, [messages]]

    